const CHUNK_SIZE_X = 1;
const CHUNK_SIZE_Y = 1;
const CHUNK_SIZE_Z = 1;

const NUMBER_CUBE_X = 20;
const NUMBER_CUBE_Y = 20;
const NUMBER_CUBE_Z = 20;

const WATER_HEIGHT = -0.3;

export {
  CHUNK_SIZE_X,
  CHUNK_SIZE_Y,
  CHUNK_SIZE_Z,
  NUMBER_CUBE_X,
  NUMBER_CUBE_Y,
  NUMBER_CUBE_Z,
  WATER_HEIGHT,
};
